#pragma once
#include "engine/bitset.h"
#include "engine/meta_defines.h"

#include <string_view>

namespace ENGINE_NS {
    namespace ecs {
        /// Component selection used to create entities and fetch matching bundles.
        ///
        /// A Query is a bitset of ComponentGid values. An entity matches a Query when
        /// all selected component bits are present in that entity's component map.
        /// Build Query values through ComponentRegister::query() rather than by
        /// constructing them directly.
        struct Query {
                /// Read/write access to the underlying component-bit selection.
                ///
                /// This reference is kept for existing call sites. Prefer using
                /// QueryBuilder when constructing new queries.
                Bitset& query = query_;

            private:
                Bitset query_{};

                Query(Bitset&& query);
                friend class QueryBuilder;
                friend class ComponentRegister;
        };

        class ComponentRegister;

        /// Fluent builder for Query objects.
        ///
        /// QueryBuilder resolves component names through the owning ComponentRegister.
        /// Selecting an unregistered component name will throw through optional::value().
        class QueryBuilder {
            public:
                /// Select a registered component by reflection name.
                auto select(std::string_view name) -> QueryBuilder&;

                /// Select a registered component type.
                ///
                /// T must expose `T::Meta::name`, normally generated by REFLECT_START.
                template <typename T>
                auto select() -> QueryBuilder& {
                    return this->select(T::Meta::name);
                }

                /// Finish and return the immutable query value.
                auto build() -> Query;

            private:
                Bitset query_{};
                const ComponentRegister& component_register_;

                friend class ComponentRegister;
                QueryBuilder(const ComponentRegister& component_register);
        };
    } // namespace ecs
} // namespace ENGINE_NS
