if(EXISTS "/home/bailey/Development/vulkan-engine/tests/engine/test_engine-b12d07c_tests.cmake")
  include("/home/bailey/Development/vulkan-engine/tests/engine/test_engine-b12d07c_tests.cmake")
else()
  add_test(test_engine_NOT_BUILT-b12d07c test_engine_NOT_BUILT-b12d07c)
endif()
